# 学习内容_201906023

---

## GO 语言顺序编程

### 类型处理

#### 类型转换
Go 语言提供了一种在不同但相互兼容的类型之间相互转换的方式，这种转换非常有用并且是安全的。但是需要注意的是在数值之间进行转换可能造成其他问题，如精度丢失或者错误的结果。以下是类型转换的语法:
```
resultOfType := Type(expression)
```
几个例子：
```
x := int16(2345)        // 声明一个类型为int16的整数，其值为2345
y := int32(x)           // 将int16类型的整数转换为int32类型
a := uint16(65000)       // 声明一个类型为uint16类型的整数
b := int16(a)           //转换为int16类型，虽然能转换成功，但是由于65000超过in16类型的范围，会导致结果错误，b的值为 -536
```

另外在 Go 语言中可以通过type关键字声明类型，如type StringsSlice []string 将[]string（string 类型的切片）声明为StringSlice类型。

#### 类型断言
在 Go 语言中接口是一个自定义类型。它声明了一个或者多个方法。任何实现了这些方法的对象（类型）都满足这个接口。

接口是完全抽象的，不能实例化。interface{} 类型表示一个空接口，任何类型都满足空接口。也就是说 interface{} 类型的值可以用于表示任意 Go 语言类型的值。

这里的空接口有点类似于 Python 语言中的 object 实例。既然 interface{} 可以用于表示任意类型，那有的时候我们需要将 interface{} 类型转换为我们需要的类型，这个操作称为类型断言。一般情况下只有我们希望表达式是某种特定类型的值时才使用类型断言。Go 语言中可以使用以下语法：
```
resultOfType, boolean := expression.(Type) // 安全的类型断言
resultOfType := expression.(Type) // 非安全的类型断言，失败时程序会产生异常
```

使用 VIM 创建源文件type_t.go，输入以下源文件：
```
package main

import (
    "fmt"
)

func main() {
    x := uint16(65000)
    y := int16(x) // 将 x转换为int16类型
    fmt.Printf("type and value of x is: %T and %d\n", x, x) // %T 格式化指令的作用是输出变量的类型
    fmt.Printf("type and value of y is: %T and %d\n", y, y)

    var i interface{} = 99 // 创建一个interface{}类型，其值为99
    var s interface{} = []string{"left", "right"}
    j := i.(int) // 我们假设i是兼容int类型，并使用类型断言将其转换为int类型
    fmt.Printf("type and value of j is: %T and %d\n", j, j)

    if s, ok := s.([]string); ok { // 创建了影子变量，if的作用域中覆盖了外部的变量s
        fmt.Printf("%T -> %q\n", s, s)
    }
}
```
![image](https://user-images.githubusercontent.com/50911356/59975077-86e9d980-95e6-11e9-97e5-d3f82842592a.png)

### 错误处理
错误处理是任何语言都需要考虑到的问题，而 Go 语言在错误处理上解决得更为完善，优雅的错误处理机制是 Go 语言的一大特点。

#### error
Go 语言引入了一个错误处理的标准模式，即error接口，该接口定义如下：
```
type error interface {
    Error() string
}
```

对于大多数函数，如果要返回错误，可以将error作为多返回值的最后一个：
```
func foo(param int)(ret int, err error)
{
  ...  
}
```

调用时的代码：
```
n, err := foo(0)
if err != nil {
    //  错误处理
} else {
    // 使用返回值n
}
```

可以自定义错误类型，创建源文件error.go，输入以下代码：
```
package main

import "fmt"
import "errors"

//自定义的出错结构
type myError struct {
    arg  int
    errMsg string
}
//实现Error接口
func (e *myError) Error() string {
    return fmt.Sprintf("%d - %s", e.arg, e.errMsg)
}

//两种出错
func error_test(arg int) (int, error) {
    if arg < 0  {
         return -1, errors.New("Bad Arguments - negtive!")
     }else if arg >256 {
        return -1, &myError{arg, "Bad Arguments - too large!"}
    }
    return arg*arg, nil
}

//相关的测试
func main() {
    for _, i := range []int{-1, 4, 1000} {
        if r, e := error_test(i); e != nil {
            fmt.Println("failed:", e)
        } else {
            fmt.Println("success:", r)
        }
    }
}
```
![image](https://user-images.githubusercontent.com/50911356/59975368-28265f00-95ea-11e9-97d7-a0b4dc454613.png)

#### defer
在 Go 函数中添加多个defer语句，当函数执行到最后时，这些 defer 语句会按照逆序执行（即最后一个defer语句将最先执行），最后该函数返回。特别是当你在进行一些打开资源的操作时，遇到错误需要提前返回，在返回前你需要关闭相应的资源，不然很容易造成资源泄露等问题。

一般写打开一个资源是这样操作的：
```
func CopyFile(dst, src string) (w int64, err error) {
    srcFile, err := os.Open(src)
    if err != nil {
        return 
    }

    defer srcFile.Close()

    dstFile, err := os.Create(dst)
    if err != nil {
        return 
    }

    defer dstFile.Close()

    return io.Copy(dstFile, srcFile)
}
```

如果defer后面一条语句干不完清理工作，也可以使用一个匿名函数：
```
defer func(){
    ...
}()
```
**注意，defer语句是在return之后执行的**

新建源文件defer.go输入以下代码：
```
func test() (result int) {
    defer func() {
        result = 12
    }()
    return 10
}

func main() {
    fmt.Println(test())     // 12
}
```
![image](https://user-images.githubusercontent.com/50911356/59975522-42ad0800-95eb-11e9-9b98-d009955c8ed2.png)
